### ISSUE TITLE
`SwiftVersion` is not decoded as expected

### ISSUE THREAD

**Issue by mflknr** [SwiftPackageIndex/SPIManifest#45]
Hey,

I'm currently adding a `.spi.yml` file to my [package](https://github.com/mflknr/swift-version-compare). While I was validating (great tool btw.) the configured `swift_version` I noticed although I'm using the rawRepresentable string "5.9" the validated output does not interpret it as the case `v5_9`. The same behavior is working the platform like "macos" -> `.macosSpm`.

Looking at the [source](https://github.com/SwiftPackageIndex/SPIManifest/blob/main/Sources/SPIManifest/SwiftVersion.swift) I also tried using `major` and `minor` with no success.

Anything that I am missing?

Here is the example YAML I used:
```yaml
version: 1
builder:
  configs:
  - platform: ios
    swift_version: '5.9'
    scheme: swift-version-compare
    target: VersionCompare
    documentation_targets: [VersionCompare]
  - platform: macos
    swift_version: '5.9'
    scheme: swift-version-compare
    target: VersionCompare
    documentation_targets: [VersionCompare]
  - platform: tvos
    swift_version: '5.9'
    scheme: swift-version-compare
    target: VersionCompare
    documentation_targets: [VersionCompare]
  - platform: watchos
    swift_version: '5.9'
    scheme: swift-version-compare
    target: VersionCompare
    documentation_targets: [VersionCompare]
  - platform: visionos
    swift_version: '5.9'
    scheme: swift-version-compare
    target: VersionCompare
    documentation_targets: [VersionCompare]
external_links:
  documentation: https://mflknr.github.io/swift-version-compare/
metadata:
  authors: 
   Marius Felkner
```
Validated:
```
Manifest(
  version: 1,
  metadata: Manifest.Metadata(
    authors: "Marius Felkner"
  ),
  builder: Manifest.Builder(
    configs: [
      [0]: Manifest.Builder.BuildConfig(
        platform: .iOS,
        swiftVersion: "5.9",
        image: nil,
        scheme: "swift-version-compare",
        target: "VersionCompare",
        documentationTargets: [
          [0]: "VersionCompare"
        ],
        customDocumentationParameters: nil
      ),
      [1]: Manifest.Builder.BuildConfig(
        platform: .macosSpm,
        swiftVersion: "5.9",
        image: nil,
        scheme: "swift-version-compare",
        target: "VersionCompare",
        documentationTargets: [
          [0]: "VersionCompare"
        ],
        customDocumentationParameters: nil
      ),
      [2]: Manifest.Builder.BuildConfig(
        platform: .tvOS,
        swiftVersion: "5.9",
        image: nil,
        scheme: "swift-version-compare",
        target: "VersionCompare",
        documentationTargets: [
          [0]: "VersionCompare"
        ],
        customDocumentationParameters: nil
      ),
      [3]: Manifest.Builder.BuildConfig(
        platform: .watchOS,
        swiftVersion: "5.9",
        image: nil,
        scheme: "swift-version-compare",
        target: "VersionCompare",
        documentationTargets: [
          [0]: "VersionCompare"
        ],
        customDocumentationParameters: nil
      ),
      [4]: Manifest.Builder.BuildConfig(
        platform: .visionOS,
        swiftVersion: "5.9",
        image: nil,
        scheme: "swift-version-compare",
        target: "VersionCompare",
        documentationTargets: [
          [0]: "VersionCompare"
        ],
        customDocumentationParameters: nil
      )
    ]
  ),
  externalLinks: Manifest.ExternalLinks(
    documentation: "https://mflknr.github.io/swift-version-compare/"
  )
)
```
And `major` / `minor` is not working either:
```yaml
swift_version:
  major: 5
  minor: 9
```
